// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
    "net/http"

    "github.com/go-openapi/runtime/middleware"

    "github.com/golang-jwt/jwt"
)

// UsersServiceCreateUserRolesHandlerFunc turns a function with the right signature into a users service create user roles handler
type UsersServiceCreateUserRolesHandlerFunc func(UsersServiceCreateUserRolesParams, *jwt.MapClaims) middleware.Responder

// Handle executing the request and returning a response
func (fn UsersServiceCreateUserRolesHandlerFunc) Handle(params UsersServiceCreateUserRolesParams, principal *jwt.MapClaims) middleware.Responder {
    return fn(params, principal)
}

// UsersServiceCreateUserRolesHandler interface for that can handle valid users service create user roles params
type UsersServiceCreateUserRolesHandler interface {
    Handle(UsersServiceCreateUserRolesParams, *jwt.MapClaims) middleware.Responder
}

// NewUsersServiceCreateUserRoles creates a new http.Handler for the users service create user roles operation
func NewUsersServiceCreateUserRoles(ctx *middleware.Context, handler UsersServiceCreateUserRolesHandler) *UsersServiceCreateUserRoles {
    return &UsersServiceCreateUserRoles{Context: ctx, Handler: handler}
}

/*
    UsersServiceCreateUserRoles swagger:route POST /api/v1/users/{id}/roles Users usersServiceCreateUserRoles

# Add roles to existing user

Add roles to existing user
*/
type UsersServiceCreateUserRoles struct {
    Context *middleware.Context
    Handler UsersServiceCreateUserRolesHandler
}

func (o *UsersServiceCreateUserRoles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
    route, rCtx, _ := o.Context.RouteInfo(r)
    if rCtx != nil {
        *r = *rCtx
    }
    var Params = NewUsersServiceCreateUserRolesParams()
    uprinc, aCtx, err := o.Context.Authorize(r, route)
    if err != nil {
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }
    if aCtx != nil {
        *r = *aCtx
    }
    var principal *jwt.MapClaims
    if uprinc != nil {
        principal = uprinc.(*jwt.MapClaims) // this is really a jwt.MapClaims, I promise
    }

    if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }

    res := o.Handler.Handle(Params, principal) // actually handle the request
    o.Context.Respond(rw, r, route.Produces, route, res)

}
