// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
    "net/http"

    "github.com/go-openapi/runtime/middleware"

    "github.com/golang-jwt/jwt"
)

// UsersServiceGetHandlerFunc turns a function with the right signature into a users service get handler
type UsersServiceGetHandlerFunc func(UsersServiceGetParams, *jwt.MapClaims) middleware.Responder

// Handle executing the request and returning a response
func (fn UsersServiceGetHandlerFunc) Handle(params UsersServiceGetParams, principal *jwt.MapClaims) middleware.Responder {
    return fn(params, principal)
}

// UsersServiceGetHandler interface for that can handle valid users service get params
type UsersServiceGetHandler interface {
    Handle(UsersServiceGetParams, *jwt.MapClaims) middleware.Responder
}

// NewUsersServiceGet creates a new http.Handler for the users service get operation
func NewUsersServiceGet(ctx *middleware.Context, handler UsersServiceGetHandler) *UsersServiceGet {
    return &UsersServiceGet{Context: ctx, Handler: handler}
}

/*
    UsersServiceGet swagger:route GET /api/v1/users/{id} Users usersServiceGet

# Get User

Get a single user by ID
*/
type UsersServiceGet struct {
    Context *middleware.Context
    Handler UsersServiceGetHandler
}

func (o *UsersServiceGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
    route, rCtx, _ := o.Context.RouteInfo(r)
    if rCtx != nil {
        *r = *rCtx
    }
    var Params = NewUsersServiceGetParams()
    uprinc, aCtx, err := o.Context.Authorize(r, route)
    if err != nil {
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }
    if aCtx != nil {
        *r = *aCtx
    }
    var principal *jwt.MapClaims
    if uprinc != nil {
        principal = uprinc.(*jwt.MapClaims) // this is really a jwt.MapClaims, I promise
    }

    if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }

    res := o.Handler.Handle(Params, principal) // actually handle the request
    o.Context.Respond(rw, r, route.Produces, route, res)

}
