// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/golang-jwt/jwt"
)

// RolesServiceGetRoleGroupsHandlerFunc turns a function with the right signature into a roles service get role groups handler
type RolesServiceGetRoleGroupsHandlerFunc func(RolesServiceGetRoleGroupsParams, *jwt.MapClaims) middleware.Responder

// Handle executing the request and returning a response
func (fn RolesServiceGetRoleGroupsHandlerFunc) Handle(params RolesServiceGetRoleGroupsParams, principal *jwt.MapClaims) middleware.Responder {
	return fn(params, principal)
}

// RolesServiceGetRoleGroupsHandler interface for that can handle valid roles service get role groups params
type RolesServiceGetRoleGroupsHandler interface {
	Handle(RolesServiceGetRoleGroupsParams, *jwt.MapClaims) middleware.Responder
}

// NewRolesServiceGetRoleGroups creates a new http.Handler for the roles service get role groups operation
func NewRolesServiceGetRoleGroups(ctx *middleware.Context, handler RolesServiceGetRoleGroupsHandler) *RolesServiceGetRoleGroups {
	return &RolesServiceGetRoleGroups{Context: ctx, Handler: handler}
}

/*
	RolesServiceGetRoleGroups swagger:route GET /api/v1/roles/{id}/groups Roles rolesServiceGetRoleGroups

# Get Role Groups

Get assigned Groups by RoleId
*/
type RolesServiceGetRoleGroups struct {
	Context *middleware.Context
	Handler RolesServiceGetRoleGroupsHandler
}

func (o *RolesServiceGetRoleGroups) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRolesServiceGetRoleGroupsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *jwt.MapClaims
	if uprinc != nil {
		principal = uprinc.(*jwt.MapClaims) // this is really a jwt.MapClaims, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
