// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/golang-jwt/jwt"
)

// SecretsServiceUndeleteSecretHandlerFunc turns a function with the right signature into a secrets service undelete secret handler
type SecretsServiceUndeleteSecretHandlerFunc func(SecretsServiceUndeleteSecretParams, *jwt.MapClaims) middleware.Responder

// Handle executing the request and returning a response
func (fn SecretsServiceUndeleteSecretHandlerFunc) Handle(params SecretsServiceUndeleteSecretParams, principal *jwt.MapClaims) middleware.Responder {
	return fn(params, principal)
}

// SecretsServiceUndeleteSecretHandler interface for that can handle valid secrets service undelete secret params
type SecretsServiceUndeleteSecretHandler interface {
	Handle(SecretsServiceUndeleteSecretParams, *jwt.MapClaims) middleware.Responder
}

// NewSecretsServiceUndeleteSecret creates a new http.Handler for the secrets service undelete secret operation
func NewSecretsServiceUndeleteSecret(ctx *middleware.Context, handler SecretsServiceUndeleteSecretHandler) *SecretsServiceUndeleteSecret {
	return &SecretsServiceUndeleteSecret{Context: ctx, Handler: handler}
}

/*
	SecretsServiceUndeleteSecret swagger:route PUT /api/v1/secrets/{id}/activate Secrets secretsServiceUndeleteSecret

# Undelete a Secret

Undelete a Secret
*/
type SecretsServiceUndeleteSecret struct {
	Context *middleware.Context
	Handler SecretsServiceUndeleteSecretHandler
}

func (o *SecretsServiceUndeleteSecret) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSecretsServiceUndeleteSecretParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *jwt.MapClaims
	if uprinc != nil {
		principal = uprinc.(*jwt.MapClaims) // this is really a jwt.MapClaims, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
