// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
    "net/http"

    "github.com/go-openapi/runtime/middleware"

    "github.com/golang-jwt/jwt"
)

// SecretsServiceUndeleteSecretV2HandlerFunc turns a function with the right signature into a secrets service undelete secret v2 handler
type SecretsServiceUndeleteSecretV2HandlerFunc func(SecretsServiceUndeleteSecretV2Params, *jwt.MapClaims) middleware.Responder

// Handle executing the request and returning a response
func (fn SecretsServiceUndeleteSecretV2HandlerFunc) Handle(params SecretsServiceUndeleteSecretV2Params, principal *jwt.MapClaims) middleware.Responder {
    return fn(params, principal)
}

// SecretsServiceUndeleteSecretV2Handler interface for that can handle valid secrets service undelete secret v2 params
type SecretsServiceUndeleteSecretV2Handler interface {
    Handle(SecretsServiceUndeleteSecretV2Params, *jwt.MapClaims) middleware.Responder
}

// NewSecretsServiceUndeleteSecretV2 creates a new http.Handler for the secrets service undelete secret v2 operation
func NewSecretsServiceUndeleteSecretV2(ctx *middleware.Context, handler SecretsServiceUndeleteSecretV2Handler) *SecretsServiceUndeleteSecretV2 {
    return &SecretsServiceUndeleteSecretV2{Context: ctx, Handler: handler}
}

/*
    SecretsServiceUndeleteSecretV2 swagger:route PUT /api/v2/secrets/{id}/activate Secrets secretsServiceUndeleteSecretV2

# Undelete a Secret

Undelete a Secret
*/
type SecretsServiceUndeleteSecretV2 struct {
    Context *middleware.Context
    Handler SecretsServiceUndeleteSecretV2Handler
}

func (o *SecretsServiceUndeleteSecretV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
    route, rCtx, _ := o.Context.RouteInfo(r)
    if rCtx != nil {
        *r = *rCtx
    }
    var Params = NewSecretsServiceUndeleteSecretV2Params()
    uprinc, aCtx, err := o.Context.Authorize(r, route)
    if err != nil {
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }
    if aCtx != nil {
        *r = *aCtx
    }
    var principal *jwt.MapClaims
    if uprinc != nil {
        principal = uprinc.(*jwt.MapClaims) // this is really a jwt.MapClaims, I promise
    }

    if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }

    res := o.Handler.Handle(Params, principal) // actually handle the request
    o.Context.Respond(rw, r, route.Produces, route, res)

}
