// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
    "net/http"

    "github.com/go-openapi/runtime/middleware"

    "github.com/golang-jwt/jwt"
)

// SecretsServiceGetGeneralHandlerFunc turns a function with the right signature into a secrets service get general handler
type SecretsServiceGetGeneralHandlerFunc func(SecretsServiceGetGeneralParams, *jwt.MapClaims) middleware.Responder

// Handle executing the request and returning a response
func (fn SecretsServiceGetGeneralHandlerFunc) Handle(params SecretsServiceGetGeneralParams, principal *jwt.MapClaims) middleware.Responder {
    return fn(params, principal)
}

// SecretsServiceGetGeneralHandler interface for that can handle valid secrets service get general params
type SecretsServiceGetGeneralHandler interface {
    Handle(SecretsServiceGetGeneralParams, *jwt.MapClaims) middleware.Responder
}

// NewSecretsServiceGetGeneral creates a new http.Handler for the secrets service get general operation
func NewSecretsServiceGetGeneral(ctx *middleware.Context, handler SecretsServiceGetGeneralHandler) *SecretsServiceGetGeneral {
    return &SecretsServiceGetGeneral{Context: ctx, Handler: handler}
}

/*
    SecretsServiceGetGeneral swagger:route GET /api/v1/secrets/secret-detail/{id}/general Secrets secretsServiceGetGeneral

# Get Secret Detail General

Retrieve details about a secret.
*/
type SecretsServiceGetGeneral struct {
    Context *middleware.Context
    Handler SecretsServiceGetGeneralHandler
}

func (o *SecretsServiceGetGeneral) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
    route, rCtx, _ := o.Context.RouteInfo(r)
    if rCtx != nil {
        *r = *rCtx
    }
    var Params = NewSecretsServiceGetGeneralParams()
    uprinc, aCtx, err := o.Context.Authorize(r, route)
    if err != nil {
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }
    if aCtx != nil {
        *r = *aCtx
    }
    var principal *jwt.MapClaims
    if uprinc != nil {
        principal = uprinc.(*jwt.MapClaims) // this is really a jwt.MapClaims, I promise
    }

    if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
        o.Context.Respond(rw, r, route.Produces, route, err)
        return
    }

    res := o.Handler.Handle(Params, principal) // actually handle the request
    o.Context.Respond(rw, r, route.Produces, route, res)

}
