// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CategorizedListSummary Query results
//
// swagger:model CategorizedListSummary
type CategorizedListSummary struct {

	// Whether or not the list is active
	Active bool `json:"active,omitempty"`

	// List Id
	CategorizedListID string `json:"categorizedListId,omitempty"`

	// Description of the list
	Description string `json:"description,omitempty"`

	// Name of the list
	Name string `json:"name,omitempty"`

	// The number of options in the list
	NumOptions int32 `json:"numOptions,omitempty"`
}

// Validate validates this categorized list summary
func (m *CategorizedListSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this categorized list summary based on context it is used
func (m *CategorizedListSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CategorizedListSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategorizedListSummary) UnmarshalBinary(b []byte) error {
	var res CategorizedListSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
