// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeletedModel Information about an object that was deleted
//
// swagger:model DeletedModel
type DeletedModel struct {

	// ID of the deleted object
	ID int32 `json:"id,omitempty"`

	// Type of the deleted object
	ObjectType string `json:"objectType,omitempty"`

	// List of response codes from the delete operation
	ResponseCodes []string `json:"responseCodes"`
}

// Validate validates this deleted model
func (m *DeletedModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this deleted model based on context it is used
func (m *DeletedModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeletedModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeletedModel) UnmarshalBinary(b []byte) error {
	var res DeletedModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
