// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ISecretSummaryExtendedField Any requested extended fields from a lookup request
//
// swagger:model ISecretSummaryExtendedField
type ISecretSummaryExtendedField struct {

	// Name
	Name string `json:"name,omitempty"`

	// Value
	Value string `json:"value,omitempty"`
}

// Validate validates this i secret summary extended field
func (m *ISecretSummaryExtendedField) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this i secret summary extended field based on context it is used
func (m *ISecretSummaryExtendedField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ISecretSummaryExtendedField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ISecretSummaryExtendedField) UnmarshalBinary(b []byte) error {
	var res ISecretSummaryExtendedField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
