// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecretDetailStateActionsModel Available Secret Detail State Actions
//
// swagger:model SecretDetailStateActionsModel
type SecretDetailStateActionsModel struct {

	// The user may extend the remaining check out time of the secret.
	ExtendCheckOut bool `json:"extendCheckOut,omitempty"`
}

// Validate validates this secret detail state actions model
func (m *SecretDetailStateActionsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret detail state actions model based on context it is used
func (m *SecretDetailStateActionsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretDetailStateActionsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretDetailStateActionsModel) UnmarshalBinary(b []byte) error {
	var res SecretDetailStateActionsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
