// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SecretFieldListType The type of list. Valid values are “None”, “Generic”, and “URL”.
//
// swagger:model SecretFieldListType
type SecretFieldListType string

func NewSecretFieldListType(value SecretFieldListType) *SecretFieldListType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated SecretFieldListType.
func (m SecretFieldListType) Pointer() *SecretFieldListType {
	return &m
}

const (

	// SecretFieldListTypeGeneric captures enum value "Generic"
	SecretFieldListTypeGeneric SecretFieldListType = "Generic"

	// SecretFieldListTypeURL captures enum value "URL"
	SecretFieldListTypeURL SecretFieldListType = "URL"

	// SecretFieldListTypeNone captures enum value "None"
	SecretFieldListTypeNone SecretFieldListType = "None"
)

// for schema
var secretFieldListTypeEnum []interface{}

func init() {
	var res []SecretFieldListType
	if err := json.Unmarshal([]byte(`["Generic","URL","None"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		secretFieldListTypeEnum = append(secretFieldListTypeEnum, v)
	}
}

func (m SecretFieldListType) validateSecretFieldListTypeEnum(path, location string, value SecretFieldListType) error {
	if err := validate.EnumCase(path, location, value, secretFieldListTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this secret field list type
func (m SecretFieldListType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateSecretFieldListTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this secret field list type based on context it is used
func (m SecretFieldListType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
