// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecretLookup Simple secret representation
//
// swagger:model SecretLookup
type SecretLookup struct {

	// Secret ID
	ID int32 `json:"id,omitempty"`

	// Secret name
	Value string `json:"value,omitempty"`
}

// Validate validates this secret lookup
func (m *SecretLookup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret lookup based on context it is used
func (m *SecretLookup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretLookup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretLookup) UnmarshalBinary(b []byte) error {
	var res SecretLookup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
