// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Sort Sort options. Multiple sort options can be provided in the query string.
//
// swagger:model Sort
type Sort struct {

	// Sort direction
	// Required: true
	Direction *SortDirection `json:"direction"`

	// Sort field name
	// Required: true
	Name *string `json:"name"`

	// Priority index. Sorts with lower values are executed earlier
	Priority int32 `json:"priority,omitempty"`
}

// Validate validates this sort
func (m *Sort) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Sort) validateDirection(formats strfmt.Registry) error {

	if err := validate.Required("direction", "body", m.Direction); err != nil {
		return err
	}

	if err := validate.Required("direction", "body", m.Direction); err != nil {
		return err
	}

	if m.Direction != nil {
		if err := m.Direction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("direction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("direction")
			}
			return err
		}
	}

	return nil
}

func (m *Sort) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this sort based on the context it is used
func (m *Sort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDirection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Sort) contextValidateDirection(ctx context.Context, formats strfmt.Registry) error {

	if m.Direction != nil {

		if err := m.Direction.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("direction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("direction")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Sort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sort) UnmarshalBinary(b []byte) error {
	var res Sort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
