// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateFieldValueOfString Description
//
// swagger:model UpdateFieldValueOfString
type UpdateFieldValueOfString struct {

	// Dirty
	Dirty bool `json:"dirty,omitempty"`

	// Value
	Value string `json:"value,omitempty"`
}

// Validate validates this update field value of string
func (m *UpdateFieldValueOfString) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update field value of string based on context it is used
func (m *UpdateFieldValueOfString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateFieldValueOfString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateFieldValueOfString) UnmarshalBinary(b []byte) error {
	var res UpdateFieldValueOfString
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
